from django.db import models


class Sale(models.Model):
    order_number_ideal = models.CharField(max_length=15)
    order_number_shop = models.TextField()
    created_at = models.TextField(blank=True, null=True)
    processed_at = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=15)
    currency = models.CharField(max_length=7, default='SOME STRING')
    total_price_with_shipping = models.IntegerField(blank=True, default=None)
    total_price_without_shipping = models.IntegerField(default=1)
    total_shipping = models.IntegerField(blank=True, default=1)
    customer_email = models.CharField(max_length=20, default='')
    customer_phone = models.TextField()
    shipping_address_address1 = models.CharField(max_length=15, default='')
    shipping_address_address2 = models.CharField(max_length=15, blank=True)
    shipping_address_city = models.CharField(max_length=15,default='')
    shipping_address_country = models.CharField(max_length=5, default='')
    shipping_address_given_name = models.CharField(max_length=10, default='')
    shipping_address_family_name = models.CharField(max_length=5,default='')
    shipping_address_zip = models.IntegerField(blank=True, default=1)
    shipping_address_salutation = models.CharField(max_length=10,default='')
    billing_address_address1 = models.CharField(max_length=10,default='')
    billing_address_address2 = models.CharField(max_length=10, blank=True)
    billing_address_city = models.CharField(max_length=10, default='')
    billing_address_country = models.CharField(max_length=3, default='')
    billing_address_given_name = models.CharField(max_length=10,default='')
    billing_address_family_name = models.CharField(max_length=10, default='')
    billing_address_zip = models.IntegerField(blank=True, default=1)
    billing_address_salutation = models.CharField(max_length=5, default='')
    fulfillment_carrier = models.CharField(max_length=10, default='')
    fulfillment_type = models.CharField(max_length=10, default='')
    fulfillment_transaction_code = models.TextField()
    fulfillment_options = models.CharField(max_length=10, blank=True)
    payment_method = models.CharField(max_length=10, default='')
    payment_transaction_id = models.CharField(max_length=20, default='')
    merchant_id = models.CharField(max_length=10, blank=True)
    merchant_name = models.CharField(max_length=10, blank=True)
    total_item_price = models.IntegerField(blank=True,default=1)
    item_price = models.IntegerField(blank=True, default=1)
    former_price = models.TextField()
    price_range_amount = models.TextField()
    quantity = models.IntegerField(blank=True,default=1)
    sku = models.CharField(max_length=20, default='')
    title = models.CharField(max_length=20, default='')
    delivery_time = models.CharField(max_length=20,default='')
    voucher_code = models.CharField(max_length=10, blank=True)
    refund_ids = models.CharField(max_length=10, blank=True)
    refund_amounts = models.TextField()
    refund_statuses = models.CharField(max_length=10, blank=True)



