# Generated by Django 3.2.16 on 2023-01-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number_ideal', models.CharField(max_length=15)),
                ('order_number_shop', models.TextField()),
                ('created_at', models.TextField(blank=True, null=True)),
                ('processed_at', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=15)),
                ('currency', models.CharField(default='SOME STRING', max_length=7)),
                ('total_price_with_shipping', models.IntegerField(blank=True, default=None)),
                ('total_price_without_shipping', models.IntegerField(default=1)),
                ('total_shipping', models.IntegerField(blank=True, default=1)),
                ('customer_email', models.CharField(default='', max_length=20)),
                ('customer_phone', models.TextField()),
                ('shipping_address_address1', models.CharField(default='', max_length=15)),
                ('shipping_address_address2', models.CharField(blank=True, max_length=15)),
                ('shipping_address_city', models.CharField(default='', max_length=15)),
                ('shipping_address_country', models.CharField(default='', max_length=5)),
                ('shipping_address_given_name', models.CharField(default='', max_length=10)),
                ('shipping_address_family_name', models.CharField(default='', max_length=5)),
                ('shipping_address_zip', models.IntegerField(blank=True, default=1)),
                ('shipping_address_salutation', models.CharField(default='', max_length=10)),
                ('billing_address_address1', models.CharField(default='', max_length=10)),
                ('billing_address_address2', models.CharField(blank=True, max_length=10)),
                ('billing_address_city', models.CharField(default='', max_length=10)),
                ('billing_address_country', models.CharField(default='', max_length=3)),
                ('billing_address_given_name', models.CharField(default='', max_length=10)),
                ('billing_address_family_name', models.CharField(default='', max_length=10)),
                ('billing_address_zip', models.IntegerField(blank=True, default=1)),
                ('billing_address_salutation', models.CharField(default='', max_length=5)),
                ('fulfillment_carrier', models.CharField(default='', max_length=10)),
                ('fulfillment_type', models.CharField(default='', max_length=10)),
                ('fulfillment_transaction_code', models.TextField()),
                ('fulfillment_options', models.CharField(blank=True, max_length=10)),
                ('payment_method', models.CharField(default='', max_length=10)),
                ('payment_transaction_id', models.CharField(default='', max_length=20)),
                ('merchant_id', models.CharField(blank=True, max_length=10)),
                ('merchant_name', models.CharField(blank=True, max_length=10)),
                ('total_item_price', models.IntegerField(blank=True, default=1)),
                ('item_price', models.IntegerField(blank=True, default=1)),
                ('former_price', models.TextField()),
                ('price_range_amount', models.TextField()),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('sku', models.CharField(default='', max_length=20)),
                ('title', models.CharField(default='', max_length=20)),
                ('delivery_time', models.CharField(default='', max_length=20)),
                ('voucher_code', models.CharField(blank=True, max_length=10)),
                ('refund_ids', models.CharField(blank=True, max_length=10)),
                ('refund_amounts', models.TextField()),
                ('refund_statuses', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
